apiVersion: apps/v1
kind: Deployment
metadata:
  name: factureservice
  labels:
    app: factureservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factureservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: factureservice
    spec:
      containers:
        - name: factureservice
          image: amineouerghi07/factureservice:1.0
          envFrom:
            - configMapRef:
                name: facture-configmap
            - secretRef:
                name: facture-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
